# Pandas: Indexing, Selection, Filtering, Cleaning, and Feature Preparation

In this notebook, we cover essential Pandas skills used in real-world data manipulation: 
- Selecting rows and columns using `.loc` and `.iloc`
- Boolean filtering and conditional selection 
- Handling missing values 
- Removing duplicates 
- Coverting data types 
- Creating new columns (feature engineering)
- Applying functions using `.apply`

These operations from the backbone of data cleaning and preparation before analysis or ML

In [72]:
import pandas as pd
import numpy as np

pd.set_option("display.max_rows", 10)
pd.set_option("display.max_columns", 20)

df = pd.read_csv("data/users.csv")
df.head()

   id     name   age         city  score signup_date  is_active
0   1    Alice  25.0     New York   88.0  2023-01-05       True
1   2      Bob  30.0  Los Angeles   92.0  2023-01-10      False
2   3  Charlie   NaN      Chicago   75.0  2023-01-12       True
3   4    David  28.0          NaN   81.0  2023-01-15       True
4   5      Eva  22.0      Houston    NaN  2023-01-20      False

## Indexing & Selection 


### Column Selection 

There are 3 common ways to select column: 
- Square brackets for a single column -> returns a **Series**
- Double brackets for multiple columns -> returns a **DataFrame** 
- Dot notation for simple column names

In [73]:
df["name"]

0        Alice
1          Bob
2      Charlie
3        David
4          Eva
        ...
145      Paula
146      Quinn
147     Rachel
148        Sam
149       Tina
Name: name, Length: 150, dtype: object

In [74]:
df[["name", "age"]]

        name   age
0      Alice  25.0
1        Bob  30.0
2    Charlie   NaN
3      David  28.0
4        Eva  22.0
..       ...   ...
145    Paula  22.0
146    Quinn   NaN
147   Rachel  29.0
148      Sam   NaN
149     Tina  27.0

[150 rows x 2 columns]

In [75]:
df.city

0         New York
1      Los Angeles
2          Chicago
3              NaN
4          Houston
          ...
145        Detroit
146        Memphis
147       New York
148    Los Angeles
149        Chicago
Name: city, Length: 150, dtype: object

### Row selection with .loc and .iloc 

1. **.loc** (label-based)
- Access rows/columns by **labels**
- Syntax: `df.loc[row_labels, column_labels]`

In [76]:
df.loc[0]

id                      1
name                Alice
age                  25.0
city             New York
score                88.0
signup_date    2023-01-05
is_active            True
Name: 0, dtype: object

In [77]:
df.loc[0, ["name", "age"]] # Return specific values from the first row

name    Alice
age      25.0
Name: 0, dtype: object

In [78]:
df.loc[0:5, ["name", "age", "city"]]

      name   age         city
0    Alice  25.0     New York
1      Bob  30.0  Los Angeles
2  Charlie   NaN      Chicago
3    David  28.0          NaN
4      Eva  22.0      Houston
5    Frank  27.0      Phoenix

2. **.iloc** (position-based)
- Access rows/columns by **integer position** 
- Syntax: `df.iloc[row_positions, column_positions]`

In [79]:
df.iloc[0]

id                      1
name                Alice
age                  25.0
city             New York
score                88.0
signup_date    2023-01-05
is_active            True
Name: 0, dtype: object

In [80]:
df.iloc[0, 0]

np.int64(1)

In [81]:
df.iloc[10:20, 1:4] # row from 10 to 20 and column from 1 to 4

      name   age           city
10   Kevin  33.0         Austin
11   Linda  24.0   Jacksonville
12    Mike  32.0     Fort Worth
13    Nina  21.0       Columbus
14   Oscar  29.0      Charlotte
15   Paula  27.0  San Francisco
16   Quinn   NaN   Indianapolis
17  Rachel  26.0        Seattle
18     Sam  34.0         Denver
19    Tina  28.0  Washington DC

## Boolean Filtering

Filtering rows with Boolean conditions 

Common operators: 
- `==`, `!=`
- `>`, `<`, `>=`, `<=`
- Combine with: 
    - `&` (AND)
    - `|` (OR)
    - `~` (NOT)

In [82]:
df[df["name"] == "Alice" ]

      id   name   age          city  score signup_date  is_active
0      1  Alice  25.0      New York   88.0  2023-01-05       True
26    27  Alice  24.0      New York   90.0  2023-03-11      False
52    53  Alice  25.0   Los Angeles    NaN  2023-04-21       True
78    79  Alice   NaN       Houston   78.0  2023-05-27      False
104  105  Alice  26.0  Philadelphia    NaN  2023-06-28       True
130  131  Alice  25.0     San Diego    NaN  2023-07-24       True

In [83]:
df[df["age"] > 25]

      id    name   age           city  score signup_date  is_active
1      2     Bob  30.0    Los Angeles   92.0  2023-01-10      False
3      4   David  28.0            NaN   81.0  2023-01-15       True
5      6   Frank  27.0        Phoenix   79.0         NaN       True
6      7   Grace  31.0   Philadelphia   84.0  2023-01-25       True
7      8  Hannah  29.0    San Antonio    NaN  2023-01-28      False
..   ...     ...   ...            ...    ...         ...        ...
136  137   Grace  29.0      Charlotte    NaN  2023-07-29       True
139  140    Jane  28.0        Seattle    NaN  2023-08-01       True
141  142   Linda  30.0  Washington DC    NaN  2023-08-02      False
147  148  Rachel  29.0       New York    NaN  2023-08-06      False
149  150    Tina  27.0        Chicago   82.0         NaN       True

[74 rows x 7 columns]

## Assignment & Modifying Data 

Always use `.loc` to safely set values 
Avoid chained indexing like `df[df["age"] >30]["salary"] = ....` because it may not modify the original DataFrame

In [84]:
df.loc[df["city"] == "New York", "city"] = "Viet Nam"
df.head()

   id     name   age         city  score signup_date  is_active
0   1    Alice  25.0     Viet Nam   88.0  2023-01-05       True
1   2      Bob  30.0  Los Angeles   92.0  2023-01-10      False
2   3  Charlie   NaN      Chicago   75.0  2023-01-12       True
3   4    David  28.0          NaN   81.0  2023-01-15       True
4   5      Eva  22.0      Houston    NaN  2023-01-20      False

## Handling Missing Data   

Key functions: 
- `df.isna()` -> True/False mask 
- `df.isna().sum()` -> count missing per column 
- `df.dropna()` -> remove rows with missing values 
- `df.fillna(x)` -> fill missing values

In [85]:
df.isna().sum()

id              0
name            0
age            44
city            3
score          51
signup_date    35
is_active       0
dtype: int64

In [86]:
df["age"] = df["age"].fillna(df["age"].median())

In [87]:
df_drop = df.dropna()
df_drop

      id     name   age          city  score signup_date  is_active
0      1    Alice  25.0      Viet Nam   88.0  2023-01-05       True
1      2      Bob  30.0   Los Angeles   92.0  2023-01-10      False
2      3  Charlie  27.5       Chicago   75.0  2023-01-12       True
6      7    Grace  31.0  Philadelphia   84.0  2023-01-25       True
8      9      Ian  26.0     San Diego   90.0  2023-02-01       True
..   ...      ...   ...           ...    ...         ...        ...
124  125      Uma  27.5   Los Angeles   74.0  2023-07-18       True
129  130     Zack  27.5   San Antonio   91.0  2023-07-22      False
133  134    David  27.5  Jacksonville   73.0  2023-07-26       True
138  139      Ian  27.5  Indianapolis   89.0  2023-07-30      False
142  143     Mike  27.5         Miami   78.0  2023-08-03       True

[61 rows x 7 columns]

## Handing Duplicates 

- `df.duplicated()` -> Boolean mask of duplicates 
- `df.drop_duplicates()` -> Remove duplicate rows

In [88]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
145    False
146    False
147    False
148    False
149    False
Length: 150, dtype: bool

In [89]:
df_no_dup = df.drop_duplicates()
df_no_dup.shape

(150, 7)

## Type Conversion 

Useful methods: 
- `df["col"].astype("int64")`
- `pd.to_datetime(df["date_col"])`

In [90]:
df["age"] = df["age"].astype("int64")
df["city"] = df["city"].astype("category")
df.dtypes

id                int64
name             object
age               int64
city           category
score           float64
signup_date      object
is_active          bool
dtype: object

## Feature Engineering 

Creating new columns using vectorized operations: 
- Arithmetic 
- Conditional columns 
- `.apply()` for custom logic

In [93]:
def check_age(age):
    if age >= 25 and age <= 30:
        return "Young"
    elif age > 30:
        return "Old"
    else: 
        return "Teenager"

df["generation"] = df["age"].apply(check_age)
df[["age", "generation"]].head()

   age generation
0   25      Young
1   30      Young
2   27      Young
3   28      Young
4   22   Teenager

In [95]:
df["age_squared"] = df["age"].apply(lambda x: x * x)
df[["age", "generation", "age_squared"]].head()

   age generation  age_squared
0   25      Young          625
1   30      Young          900
2   27      Young          729
3   28      Young          784
4   22   Teenager          484